Re-enable `check-fuzzgen` CI step (#4206)
## Motivation and Context
https://github.com/smithy-lang/smithy-rs/issues/4195
```
FuzzHarnessBuildPluginTest > smokeTest() FAILED
    CommandError(output=Unexpected exception thrown when executing subprocess:
    CommandError(output=Command Error
    warning: /Users/awsaito/.local/share/smithy-test-workspace/smithy-test9654713374929678826/a/Cargo.toml: unused manifest key: workspace._ignored
        Updating crates.io index
         Locking 300 packages to latest compatible versions
          Adding homedir v0.3.6 (requires Rust 1.88)
    error: rustc 1.85.0 is not supported by the following package:
      homedir@0.3.6 requires rustc 1.88
    Either upgrade rustc or select compatible dependency versions with
    `cargo update <name>@<current-ver> --precise <compatible-ver>`
    where `<compatible-ver>` is the latest version supporting rustc 1.85.0
```

## Description
The PR commits a new lockfile to the `aws-smithy-fuzz` crate, which
contains a downgraded `homedir` crate with version `0.3.5`.
`FuzzHarnessBuildPlugin` places that lockfile in a fuzz target workspace
to avoid the compilation error above.

As a follow-up, filed [an OPS
enhancement](https://github.com/smithy-lang/smithy-rs/issues/4205) to
improve the lockfile update workflow to handle the one in
`aws-smithy-fuzz` as well.

----

_By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice._