Pin `minicbor` to 0.24.2 (#3818)
**Will merge to the release branch**

## Motivation and Context
Fixes a failure observed in our release pipeline

## Description
A lockfile located at `aws/sdk/Cargo.lock` did not include the
`minicbor` crate that was introduced as part of RPC V2 CBOR. This has
caused a build failure in our release pipeline due to a new version of
`minicbor` 0.24.3 uploaded to crates.io.
```
error: unsupported output in build script of `minicbor v0.24.3`: `cargo::rustc-check-cfg=cfg(atomic64, atomic32)`
```

To address this issue, this PR pins `minicbor` to 0.24.2 in
`aws/sdk/Cargo.lock` (`rust-runtime/Cargo.lock` already pins it to
0.24.2)

The change in `aws/sdk/Cargo.lock` was obtained by
1. running `git pull` in `/Users/awsaito/src/aws-sdk-rust`
2. running `./gradlew aws:sdk:generateAllLockfiles
-Paws-sdk-rust-path=/Users/awsaito/src/aws-sdk-rust`
3. retaining the portion only relevant to `minicbor`

In addition, since the release of aws-sdk-rust the other day, smoke
tests have started getting rendered and compiled in cargo-semver-checks.
This has caused cargo-semver-checks to exceed the previous timeout of 20
minutes. To address it, we have increased the timeout to 30 minutes.

## Testing
- [ ] Tests in CI
- [x] End-to-end tests in our release pipeline

----

_By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice._