Replace `doc_auto_cfg` with `doc_cfg` to allow docsrs build to succeed (#4331)
## Motivation and Context
<!--- Why is this change required? What problem does it solve? -->
<!--- If it fixes an open issue, please link to the issue here -->
Our docrs builds started
[failing](https://docs.rs/crate/aws-sdk-dynamodb/1.94.0/builds/2555063)
recently with the error:
```
[INFO] [stderr]  Documenting aws-sdk-dynamodb v1.94.0 (/opt/rustwide/workdir)
[INFO] [stderr] error[E0557]: feature has been removed
[INFO] [stderr]   --> src/lib.rs:21:29
[INFO] [stderr]    |
[INFO] [stderr] 21 | #![cfg_attr(docsrs, feature(doc_auto_cfg))]
[INFO] [stderr]    |                             ^^^^^^^^^^^^ feature has been removed
[INFO] [stderr]    |
[INFO] [stderr]    = note: removed in CURRENT_RUSTC_VERSION; see <https://github.com/rust-lang/rust/pull/138907> for more information
[INFO] [stderr]    = note: merged into `doc_cfg`
[INFO] [stderr] 
[INFO] [stderr] error: Compilation failed, aborting rustdoc
[INFO] [stderr] 
[INFO] [stderr] For more information about this error, try `rustc --explain E0557`.
[INFO] [stderr] error: could not document `aws-sdk-dynamodb`
```

The [linked issue](https://github.com/rust-lang/rust/pull/138907) shows
that `doc_auto_cfg` has recently been merged into `doc_cfg`. docsrs
builds with the latest nightly toolchain, so the change has impacted our
doc builds. This PR makes that change in codegen and in all of our
runtime crates.

## Checklist
<!--- If a checkbox below is not applicable, then please DELETE it
rather than leaving it unchecked -->
- [ ] For changes to the smithy-rs codegen or runtime crates, I have
created a changelog entry Markdown file in the `.changelog` directory,
specifying "client," "server," or both in the `applies_to` key.
- [ ] For changes to the AWS SDK, generated SDK code, or SDK runtime
crates, I have created a changelog entry Markdown file in the
`.changelog` directory, specifying "aws-sdk-rust" in the `applies_to`
key.

----

_By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice._