fix: Fixing Unknown union member case in JMESPath codegen (#4741)
## Motivation and Context
This is a followup fix for this change:
https://github.com/smithy-lang/smithy-rs/pull/4726#issue-4769121152

Solves a case in which `union` shapes in the smithy model have members
named `unknown`/`Unknown`.

There's a collision in our client generation here with the default
`Unknown`
[variant](https://github.com/smithy-lang/smithy-rs/blob/main/codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/smithy/generators/UnionGenerator.kt#L95)
generated for all union enums. Without this change, generated client
code on unions with `unknown`/`Unknown` members will fail with errors
like

```
       Compiling test_smithy-test14186278412878790130 v1.0.0 (/local/home/mjcream/.local/share/smithy-test-workspace/smithy-test14186278412878790130)
    error[E0532]: expected tuple struct or tuple variant, found unit variant `crate::types::Status::Unknown`
        --> smithy-test14186278412878790130/src/lib.rs:1520:13
         |
    1520 |             crate::types::Status::Unknown(_) => "unknown".to_string(),
         |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         |
        ::: smithy-test14186278412878790130/src/types/_status.rs:24:5
         |
      24 |     Unknown,
         |     ------- `crate::types::Status::Unknown` defined here
         |
    help: use this syntax instead
         |
    1520 -             crate::types::Status::Unknown(_) => "unknown".to_string(),
    1520 +             crate::types::Status::Unknown => "unknown".to_string(),
         |
    help: consider importing this tuple variant instead
         |
      51 + use crate::types::Enum::Unknown;
         |
    help: if you import `Unknown`, refer to it directly
         |
    1520 -             crate::types::Status::Unknown(_) => "unknown".to_string(),
    1520 +             Unknown(_) => "unknown".to_string(),
         |
```

**Note**: this is not the fix for
https://github.com/smithy-lang/smithy-rs/issues/4096, but the problem's
related in nature. That issue is related to the collision for [these
generated `is_...` methods with
`is_unknown`](https://github.com/smithy-lang/smithy-rs/blob/main/codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/smithy/generators/UnionGenerator.kt#L121-L131)

## Description
~~This PR skips explicit match arms for `unknown`/`Unknown` union
members in `RustJmespathShapeTraversalGenerator` for the `keys`
implementation, since that collides with the synthetic `Unknown` unit
variant that client codegen adds to every union for forward
compatibility. See
[UnionGenerator.kt](https://github.com/smithy-lang/smithy-rs/blob/main/codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/smithy/generators/UnionGenerator.kt#L95)~~

This PR uses the renamed symbols for the enum variants instead of the
raw union member names, avoiding a collision with the synthetic
`Unknown` unit variant that client codegen adds to every union for
forward compatibility. See
[UnionGenerator.kt](https://github.com/smithy-lang/smithy-rs/blob/main/codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/smithy/generators/UnionGenerator.kt#L95)

We have this `Unknown` variant in place for forward compatibility for
responses when the server adds new variants.

For the following union, the match statement in the generated
`src/waiters/matcher.rs` client code is below:
```
union JobStatus {
    pending: StatusPending,
    running: StatusRunning,
    done: StatusDone,
    failed: StatusFailed,
    unknown: StatusUnknown
}

/// Matcher union: {"output":{"path":"keys(jobStatus)","expected":"done","comparator":"allStringEquals"}}
pub(crate) fn match_get_my_job_results_cb252c27504256efe(
    ...
) -> bool {
    fn path_traversal<'a>(
        ...
    ) -> ::std::option::Option<::std::vec::Vec<::std::string::String>> {
...
        let _ret_1 = vec![match _fld_2 {
            crate::types::JobStatus::Pending(_) => "pending".to_string(),
            crate::types::JobStatus::Running(_) => "running".to_string(),
            crate::types::JobStatus::Done(_) => "done".to_string(),
            crate::types::JobStatus::Failed(_) => "failed".to_string(),
            crate::types::JobStatus::UnknownValue(_) => "unknown".to_string(),
            _ => "unknown".to_string(),
        }];
...
```

## Testing
* Added the `unknown` member to the test union to exercise this case.
* `./gradlew :codegen-client:test` passes

### Does ignoring the Union member in the enum matter?
For our purposes, we don't need the union contents, the JMESPath `keys`
implementation only requires us to get the string representation of the
union member name.

## Checklist
- [x] For changes to the smithy-rs codegen or runtime crates, I have
created a changelog entry Markdown file in the `.changelog` directory,
specifying "client," "server," or both in the `applies_to` key.

----

_By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice._

---------

Co-authored-by: Landon James <lnj@amazon.com>