Squashed commit of the following:
commit efb8baa809fc1ed034d907b7498c5fda752a54e4
Author: Thomas Cameron <68596478+thomas-k-cameron@users.noreply.github.com>
Date:   Thu Apr 13 18:11:42 2023 +0000

    pre-commit

commit 36354579b7d267ccdfbb1c95005cfe148a9a8d94
Author: Thomas Cameron <68596478+thomas-k-cameron@users.noreply.github.com>
Date:   Thu Apr 13 17:56:24 2023 +0000

    typo

commit 3d6cb3bc0d967b5a10bb6700a63edb21fb5b313a
Author: Thomas Cameron <68596478+thomas-k-cameron@users.noreply.github.com>
Date:   Thu Apr 13 17:50:12 2023 +0000

    update

commit 57d2ee33d0e38463f8a81048e89344838d8631a3
Author: Thomas Cameron <68596478+thomas-k-cameron@users.noreply.github.com>
Date:   Thu Apr 13 17:40:11 2023 +0000

    update

commit 0ac596a33cab63d8b025aac220933c7ac9646ccc
Author: Thomas Cameron <68596478+thomas-k-cameron@users.noreply.github.com>
Date:   Thu Apr 13 17:25:36 2023 +0000

    pre-commit

commit 8aa98e999bd170707347c470f23510187e415109
Author: Thomas Cameron <68596478+thomas-k-cameron@users.noreply.github.com>
Date:   Thu Apr 13 17:24:59 2023 +0000

    Fix

commit 924f0e5a3b1dd5bff5b7360678a2740abeecca9e
Author: Thomas Cameron <68596478+thomas-k-cameron@users.noreply.github.com>
Date:   Thu Apr 13 17:24:21 2023 +0000

    - line break
    - add aws-sdk-unstable
    - bug fix

commit dee9fd5f896d9ca707037d7312f48085a3500390
Author: Thomas Cameron <68596478+thomas-k-cameron@users.noreply.github.com>
Date:   Thu Apr 13 16:58:19 2023 +0000

    FIX doctest

commit b535e79b065d979324dcf16f885090201446982f
Author: Thomas Cameron <68596478+thomas-k-cameron@users.noreply.github.com>
Date:   Thu Apr 13 16:47:07 2023 +0000

    FIX doc error

commit a44a79fcf845f03ab2c8cf0a2443d64ec2a15007
Author: Thomas Cameron <68596478+thomas-k-cameron@users.noreply.github.com>
Date:   Wed Apr 12 19:50:57 2023 +0000

    Upon closerinspection, it appears that the test didn't make any sense

commit 238b517e731b0b526c00bba880a37035784790c4
Author: Thomas Cameron <68596478+thomas-k-cameron@users.noreply.github.com>
Date:   Wed Apr 12 19:39:40 2023 +0000

        error: test failed, to rerun pass `--lib`

        running 1 test
        test smithy_codegen_serde_features ... FAILED

        failures:

        ---- smithy_codegen_serde_features stdout ----
        thread 'smithy_codegen_serde_features' panicked at 'assertion failed: `(left == right)`
          left: `None`,
         right: `Some(["serde-serialize", "serde-deserialize"])`', smithy-test8434519010247410672/src/lib.rs:18:5
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

        failures:
            smithy_codegen_serde_features

        test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.09s

        ))
            at app//software.amazon.smithy.rust.codegen.core.util.ExecKt.runCommand(Exec.kt:40)
            at app//software.amazon.smithy.rust.codegen.core.util.ExecKt.runCommand$default(Exec.kt:14)
            at app//software.amazon.smithy.rust.codegen.core.testutil.RustKt.compileAndTest(Rust.kt:340)
            at app//software.amazon.smithy.rust.codegen.core.testutil.RustKt.compileAndTest$default(Rust.kt:316)
            at app//software.amazon.smithy.rust.codegen.core.smithy.generators.CargoTomlGeneratorTest.check serde features(CargoTomlGeneratorTest.kt:71)

commit 30af65a5dc2fc6fea5c7be4f35dba192c0995471
Author: Thomas Cameron <68596478+thomas-k-cameron@users.noreply.github.com>
Date:   Wed Apr 12 19:38:35 2023 +0000

           Compiling test_smithy-test15870661464884769120 v0.0.1 (/home/codespace/.local/share/smithy-test-workspace/smithy-test15870661464884769120)
        error[E0308]: mismatched types
          --> smithy-test15870661464884769120/src/lib.rs:18:5
           |
        18 | /     assert_eq!(
        19 | |         features.get("aws-aws-smithy-types"),
        20 | |         Some(vec![
        21 | |             "serde-serialize".to_string(),
        22 | |             "serde-deserialize".to_string()
        23 | |         ])
        24 | |     );
           | |_____^ expected `&Vec<String>`, found struct `Vec`
           |
           = note: expected enum `Option<&Vec<String>>`
                      found enum `Option<Vec<String>>`
           = note: this error originates in the macro `assert_eq` (in Nightly builds, run with -Z macro-backtrace for more info)

        For more information about this error, try `rustc --explain E0308`.
        error: could not compile `test_smithy-test15870661464884769120` due to previous error

        ))
            at app//software.amazon.smithy.rust.codegen.core.util.ExecKt.runCommand(Exec.kt:40)
            at app//software.amazon.smithy.rust.codegen.core.util.ExecKt.runCommand$default(Exec.kt:14)
            at app//software.amazon.smithy.rust.codegen.core.testutil.RustKt.compileAndTest(Rust.kt:340)
            at app//software.amazon.smithy.rust.codegen.core.testutil.RustKt.compileAndTest$default(Rust.kt:316)
            at app//software.amazon.smithy.rust.codegen.core.smithy.generators.CargoTomlGeneratorTest.check serde features(CargoTomlGeneratorTest.kt:71)

commit 51dc9cb7ad92cbce14a02ca022d005933b2b7bda
Author: Thomas Cameron <68596478+thomas-k-cameron@users.noreply.github.com>
Date:   Wed Apr 12 19:37:09 2023 +0000

    Fixes failing tests.
           Compiling test_smithy-test10848989719950068844 v0.0.1 (/home/codespace/.local/share/smithy-test-workspace/smithy-test10848989719950068844)
        error[E0308]: mismatched types
          --> smithy-test10848989719950068844/src/lib.rs:18:5
           |
        18 | /     assert_eq!(
        19 | |         features.get("aws-aws-smithy-types"),
        20 | |         Some(vec![
        21 | |             "serde-serialize".to_string(),
        22 | |             "serde-deserialize".to_string()
        23 | |         ])
        24 | |     );
           | |_____^ expected `&Vec<String>`, found struct `Vec`
           |
           = note: expected enum `Option<&Vec<String>>`
                      found enum `Option<Vec<String>>`
           = note: this error originates in the macro `assert_eq` (in Nightly builds, run with -Z macro-backtrace for more info)

        For more information about this error, try `rustc --explain E0308`.
        error: could not compile `test_smithy-test10848989719950068844` due to previous error

        ))
            at app//software.amazon.smithy.rust.codegen.core.util.ExecKt.runCommand(Exec.kt:40)
            at app//software.amazon.smithy.rust.codegen.core.util.ExecKt.runCommand$default(Exec.kt:14)
            at app//software.amazon.smithy.rust.codegen.core.testutil.RustKt.compileAndTest(Rust.kt:340)
            at app//software.amazon.smithy.rust.codegen.core.testutil.RustKt.compileAndTest$default(Rust.kt:316)
            at app//software.amazon.smithy.rust.codegen.core.smithy.generators.CargoTomlGeneratorTest.check serde features(CargoTomlGeneratorTest.kt:71)

commit d2520175995ac90cecb8fbd5d7f8503fcff3747d
Author: Thomas Cameron <68596478+thomas-k-cameron@users.noreply.github.com>
Date:   Wed Apr 12 19:33:08 2023 +0000

    update

commit 12d56fe7de129d2601d6a32dc1bd2a9ea87f6813
Author: Thomas Cameron <68596478+thomas-k-cameron@users.noreply.github.com>
Date:   Wed Apr 12 19:22:54 2023 +0000

    Merge commit 'a87b41587f311214c3fc8169c8b41ece9c10fe2b'

commit 2ad85a956ee7b57b48dd030bbce46456240cbbdb
Author: Thomas Cameron <68596478+thomas-k-cameron@users.noreply.github.com>
Date:   Wed Apr 12 19:15:09 2023 +0000

    update

commit 49065706b9fc872642be96c144b6165f7929b3c9
Author: Thomas Cameron <68596478+thomas-k-cameron@users.noreply.github.com>
Date:   Wed Apr 12 19:07:11 2023 +0000

    FIX

commit 51d1e6b83a738b2fd5562db1a86e2f4b133f51f4
Author: Thomas Cameron <68596478+thomas-k-cameron@users.noreply.github.com>
Date:   Wed Apr 12 19:00:01 2023 +0000

    FIX

commit dec2ad16a056ad73b50086a67d37bd5abc6b75c3
Author: Thomas Cameron <68596478+thomas-k-cameron@users.noreply.github.com>
Date:   Wed Apr 12 18:50:57 2023 +0000

    FIX

commit c0d947072bf743b8a01439130ed8b499b4b6e1fd
Author: Thomas Cameron <68596478+thomas-k-cameron@users.noreply.github.com>
Date:   Wed Apr 12 18:42:59 2023 +0000

    FIX
    error: casting to the same type is unnecessary (`f64` -> `f64`)
      --> aws-smithy-types/src/number.rs:41:33
       |
    41 |             Number::Float(v) => v as f64,
       |                                 ^^^^^^^^ help: try: `v`
       |
       = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast
       = note: `-D clippy::unnecessary-cast` implied by `-D warnings`

commit e60c057c122697c14defcdcb2fadb6a4bc033c6d
Author: Thomas Cameron <68596478+thomas-k-cameron@users.noreply.github.com>
Date:   Wed Apr 12 18:20:52 2023 +0000

    precommit