fix derive-arbitrary feature for aws-smithy-eventstreams (#4269)
## Description
Latest CI run of the SDK failed
https://github.com/awslabs/aws-sdk-rust/actions/runs/16974016317/job/48118142608


```
   Compiling aws-smithy-eventstream v0.60.10 (/home/runner/work/aws-sdk-rust/aws-sdk-rust/sdk/aws-smithy-eventstream)
error[E0433]: failed to resolve: could not find `details` in `arbitrary`
   --> sdk/aws-smithy-eventstream/src/arbitrary.rs:65:35
    |
65  | #[derive(Clone, Debug, PartialEq, derive_arbitrary::Arbitrary)]
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `details` in `arbitrary`
    |
note: found an item that was configured out
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/arbitrary-1.4.2/src/lib.rs:558:9
    |
558 | pub mod details {
    |         ^^^^^^^
note: the item is gated behind the `derive` feature
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/arbitrary-1.4.2/src/lib.rs:557:7
    |
557 | #[cfg(feature = "derive")]
    |       ^^^^^^^^^^^^^^^^^^
    = note: this error originates in the derive macro `derive_arbitrary::Arbitrary` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0433`.
error: could not compile `aws-smithy-eventstream` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
Traceback (most recent call last):
  File "/home/runner/work/aws-sdk-rust/aws-sdk-rust/./tools/ci/crate-range.py", line 286, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/runner/work/aws-sdk-rust/aws-sdk-rust/./tools/ci/crate-range.py", line 204, in main
    return subcommand_run(repository_root, args.batches, args.start_inclusive, args.end_exclusive, args.folder, args.cmd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/aws-sdk-rust/aws-sdk-rust/./tools/ci/crate-range.py", line 167, in subcommand_run
    subprocess.run(command, check=True)
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cargo', 'test', '--all-features']' returned non-zero exit status 101.
Error: Process completed with exit code 1.
```



Looks like `arbitrary` crate released `1.4.2` yesterday and it's now
triggering this for us. I looked at the changes but didn't see anything
obvious on their end. Either way I don't think we ever had our
`Cargo.toml` right though for enabling the required feature.

## Checklist
<!--- If a checkbox below is not applicable, then please DELETE it
rather than leaving it unchecked -->
- [x] For changes to the smithy-rs codegen or runtime crates, I have
created a changelog entry Markdown file in the `.changelog` directory,
specifying "client," "server," or both in the `applies_to` key.
- [x] For changes to the AWS SDK, generated SDK code, or SDK runtime
crates, I have created a changelog entry Markdown file in the
`.changelog` directory, specifying "aws-sdk-rust" in the `applies_to`
key.

----

_By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice._