Avoid a real connection in unit test (#3063)
## Motivation and Context
Fixes a flaky test that misbehaves as follows:
```
---- tests_1::test_specifying_credentials_provider_only_at_operation_level_should_work stdout ----
thread 'tests_1::test_specifying_credentials_provider_only_at_operation_level_should_work' panicked at 'success: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Io, sour
ce: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 110, kind: TimedOut, message: "Connection timed out" })), connection: Unknown } })', smithy-test9200972819374912606/src
/lib.rs:105:14
```

## Description
Because the fix is meant for the release branch, it uses a
`TestConnection` rather than a `StaticReplayClient`, which is available
only in the `main` branch. Code needs to be upgraded when the PR is
back-ported to the `main` branch.

----

_By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice._