Update check-aws-sdk-smoketest-docs-clippy-udeps to run on 16 core runner (#4552)
## Motivation and Context
<!--- Why is this change required? What problem does it solve? -->
<!--- If it fixes an open issue, please link to the issue here -->

The `check-aws-sdk-smoketest-docs-clippy-udeps` CI task keeps randomly
failing
([ex](https://github.com/smithy-lang/smithy-rs/actions/runs/22590637962/job/65453017445)).
The errors don't offer much in the way of explanation:
```

 Documenting aws-sdk-s3control v0.0.0-local (/home/build/workspace/aws-sdk-smoketest/sdk/s3control)
error: could not document `aws-sdk-codecatalyst`

Caused by:
  process didn't exit successfully: `/opt/rustup/toolchains/nightly-2025-10-18-x86_64-unknown-linux-gnu/bin/rustdoc --edition=2021 --crate-type lib --crate-name aws_sdk_codecatalyst sdk/codecatalyst/src/lib.rs -o /home/build/workspace/aws-sdk-smoketest/target/doc --cfg 'feature="behavior-version-latest"' --cfg 'feature="default"' --cfg 'feature="default-https-client"' --cfg 'feature="gated-tests"' --cfg 'feature="rt-tokio"' --cfg 'feature="rustls"' --cfg 'feature="test-util"' --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values("behavior-version-latest", "default", "default-https-client", "gated-tests", "rt-tokio", "rustls", "test-util"))' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -C metadata=2e5ab7ac4e9c9be3 -L dependency=/home/build/workspace/aws-sdk-smoketest/target/debug/deps --extern aws_credential_types=/home/build/workspace/aws-sdk-smoketest/target/debug/deps/libaws_credential_types-451c492649c6e63e.rmeta --extern aws_runtime=/home/build/workspace/aws-sdk-smoketest/target/debug/deps/libaws_runtime-cb3a916d393b367b.rmeta --extern aws_smithy_async=/home/build/workspace/aws-sdk-smoketest/target/debug/deps/libaws_smithy_async-245672a92c8fbc71.rmeta --extern aws_smithy_http=/home/build/workspace/aws-sdk-smoketest/target/debug/deps/libaws_smithy_http-e17aab374c6c68cf.rmeta --extern aws_smithy_json=/home/build/workspace/aws-sdk-smoketest/target/debug/deps/libaws_smithy_json-a0b5b6e49b0bbff3.rmeta --extern aws_smithy_observability=/home/build/workspace/aws-sdk-smoketest/target/debug/deps/libaws_smithy_observability-215e8411a190a694.rmeta --extern aws_smithy_runtime=/home/build/workspace/aws-sdk-smoketest/target/debug/deps/libaws_smithy_runtime-9b5a3fd0e1312563.rmeta --extern aws_smithy_runtime_api=/home/build/workspace/aws-sdk-smoketest/target/debug/deps/libaws_smithy_runtime_api-c3534e96fd1d870d.rmeta --extern aws_smithy_types=/home/build/workspace/aws-sdk-smoketest/target/debug/deps/libaws_smithy_types-6afac6fe622472bf.rmeta --extern aws_types=/home/build/workspace/aws-sdk-smoketest/target/debug/deps/libaws_types-2626be274c5ee4b5.rmeta --extern bytes=/home/build/workspace/aws-sdk-smoketest/target/debug/deps/libbytes-21355aedf016ddad.rmeta --extern fastrand=/home/build/workspace/aws-sdk-smoketest/target/debug/deps/libfastrand-9455f55740270982.rmeta --extern http=/home/build/workspace/aws-sdk-smoketest/target/debug/deps/libhttp-9ca25fea75741670.rmeta --extern http_1x=/home/build/workspace/aws-sdk-smoketest/target/debug/deps/libhttp-9cff19b8f9e1db56.rmeta --extern regex_lite=/home/build/workspace/aws-sdk-smoketest/target/debug/deps/libregex_lite-d156dfd96ad510a1.rmeta --extern tracing=/home/build/workspace/aws-sdk-smoketest/target/debug/deps/libtracing-659223e41eed5f54.rmeta --document-private-items --cfg docsrs --crate-version 0.0.0-local` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
```

But it seems likely that this is related to hitting some kind of
resource limit. I am bumping the runner type to 16 core for this task to
hopefully help it pass consistently.

## Testing
<!--- Please describe in detail how you tested your changes -->
<!--- Include details of your testing environment, and the tests you ran
to -->
<!--- see how your change affects other areas of the code, etc. -->
The CI for `check-aws-sdk-smoketest-docs-clippy-udeps` will hopefully
pass, but that isn't proof that this is a true fix since it will
intermittently pass in the current state.

----

_By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice._