Bump MSRV to 1.82 (#4120)
## Motivation and Context
Bumps MRSV to 1.82.0

## Description
This resolves issues observed in CI and the release pipeline where newer
dependencies require newer MSRV:
```
error: rustc 1.81.0 is not supported by the following packages:
  icu_collections@2.0.0 requires rustc 1.82
  icu_locale_core@2.0.0 requires rustc 1.82
  icu_normalizer@2.0.0 requires rustc 1.82
  icu_normalizer_data@2.0.0 requires rustc 1.82
  icu_normalizer_data@2.0.0 requires rustc 1.82
  icu_normalizer_data@2.0.0 requires rustc 1.82
  icu_properties@2.0.0 requires rustc 1.82
  icu_properties_data@2.0.0 requires rustc 1.82
  icu_properties_data@2.0.0 requires rustc 1.82
  icu_properties_data@2.0.0 requires rustc 1.82
  icu_provider@2.0.0 requires rustc 1.82
  idna_adapter@1.2.1 requires rustc 1.82
  litemap@0.8.0 requires rustc 1.82
  zerotrie@0.2.2 requires rustc 1.82
  zerovec@0.11.2 requires rustc 1.82
```

Why did dependencies get upgraded in spite of lockfiles, is [tracked
separately](https://github.com/smithy-lang/smithy-rs/issues/4121).

## Testing
CI

## Checklist
<!--- If a checkbox below is not applicable, then please DELETE it
rather than leaving it unchecked -->
- [x] For changes to the smithy-rs codegen or runtime crates, I have
created a changelog entry Markdown file in the `.changelog` directory,
specifying "client," "server," or both in the `applies_to` key.
- [x] For changes to the AWS SDK, generated SDK code, or SDK runtime
crates, I have created a changelog entry Markdown file in the
`.changelog` directory, specifying "aws-sdk-rust" in the `applies_to`
key.

----

_By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice._